require_relative 'tasks/authentication/login'
require_relative 'tasks/authentication/ensure'
require_relative 'tasks/pipeline/get'
require_relative 'tasks/pipeline/set'
require_relative 'tasks/pipeline/unpause'
require_relative 'tasks/pipeline/push'
require_relative 'tasks/pipeline/destroy'
